image: aoepeople/fe-build-env:1.4.0

stages:
- test
- build
- publish

cache:
  paths:
  - akl/frontend/node_modules/
  - lhr/frontend/node_modules/
  - vendor/
  key: "$CI_COMMIT_REF_NAME"

test flamingo:
  stage: test
  image: thebod/goenv:0.0.1
  script:
  - export GODIR="${GOPATH}/src/go.aoe.com/flamingo"
  - ln -sfv "$(pwd -P)" "${GODIR}"
  - /pact/pact-go_linux_amd64 daemon &
  - cd "${GODIR}"
  - dep ensure -vendor-only
  - go test ./...

test frontend akl:
  stage: test
  script:
  - cd akl/frontend
  - yarn
  - npm rebuild node-sass
  - yarn test
  - yarn run build
  artifacts:
    expire_in: 2 days
    paths:
    - akl/frontend/dist

test frontend lhr:
  stage: test
  script:
  - cd lhr/frontend
  - yarn
  - npm rebuild node-sass
  - yarn test
  - yarn run build
  artifacts:
    expire_in: 2 days
    paths:
    - lhr/frontend/dist

build akl:
  stage: build
  image: thebod/goenv:0.0.1
  script:
  - export GODIR="${GOPATH}/src/go.aoe.com/flamingo"
  - ln -sfv "$(pwd -P)" "${GODIR}"
  - cd "${GODIR}/akl"
  - dep ensure -vendor-only
  - CGO_ENABLED=0 go build .
  artifacts:
    expire_in: 2 days
    paths:
    - akl/akl
  dependencies:
  - test flamingo
  - test frontend akl

build lhr:
  stage: build
  image: thebod/goenv:0.0.1
  script:
  - export GODIR="${GOPATH}/src/go.aoe.com/flamingo"
  - ln -sfv "$(pwd -P)" "${GODIR}"
  - cd "${GODIR}/lhr"
  - dep ensure -vendor-only
  - CGO_ENABLED=0 go build .
  artifacts:
    expire_in: 2 days
    paths:
    - lhr/lhr
  dependencies:
  - test flamingo
  - test frontend lhr

publish akl:
  stage: publish
  image: docker
  dependencies:
  - build akl
  - test frontend akl
  script:
  - cd akl
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} docker-om3-akl.aoe.com
  - docker build -t docker-om3-akl.aoe.com/flamingo:latest .
  - docker push docker-om3-akl.aoe.com/flamingo:latest
  only:
  - master

publish lhr:
  stage: publish
  image: docker
  dependencies:
  - build lhr
  - test frontend lhr
  script:
  - cd lhr
  #- docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} docker-om3-lhr.aoe.com
  - docker login -u ${DOCKER_LHR_USER} -p ${DOCKER_LHR_PASSWORD} docker-om3-lhr.aoe.com
  - docker build -t docker-om3-lhr.aoe.com/flamingo:latest .
  - docker push docker-om3-lhr.aoe.com/flamingo:latest
  only:
  - master
