stages:
- test
- build
- publish

test flamingo:
  stage: test
  image: thebod/goenv:0.0.1
  script:
  - export GODIR="${GOPATH}/src/flamingo"
  - ln -sfv "$(pwd -P)" "${GODIR}"
  - /pact/pact-go_linux_amd64 daemon &
  - cd "${GODIR}"
  - dep ensure -vendor-only
  - go test ./...
  variables:
    PACT_DAEMON_HOST: pact
  cache:
    paths:
    - vendor/

test frontend akl:
  stage: test
  image: aoepeople/fe-build-env:1.3.0
  script:
  - cd akl/frontend
  - yarn install
  - npm rebuild node-sass
  - yarn test
  cache:
    paths:
    - akl/frontend/node_modules/

test frontend lhr:
  image: aoepeople/fe-build-env:1.3.0
  stage: test
  script:
  - cd akl/frontend
  - yarn install
  - npm rebuild node-sass
  - yarn test
  cache:
    paths:
    - akl/frontend/node_modules/

build akl:
  stage: build
  image: golang:1.9
  script:
  - export GODIR="${GOPATH}/src/flamingo"
  - ln -sfv "$(pwd -P)" "${GODIR}"
  - cd "${GODIR}/akl"
  - go build .
  cache:
    paths:
    - vendor/
  artifacts:
    paths:
    - akl/akl
  dependencies:
  - test flamingo
  - test frontend akl

build lhr:
  stage: build
  image: golang:1.9
  script:
  - export GODIR="${GOPATH}/src/flamingo"
  - ln -sfv "$(pwd -P)" "${GODIR}"
  - cd "${GODIR}/lhr"
  - go build .
  cache:
    paths:
    - vendor/
  artifacts:
    paths:
    - lhr/lhr
  dependencies:
  - test flamingo
  - test frontend akl

publish akl:
  stage: publish
  image: docker
  script:
  - docker build
