stages:
- prepare
- test

build docker env:
  stage: prepare
  image: docker:latest
  script:
  - cd build/docker
  - docker login -uiloveflamingobot -p${DOCKERPASSWORD}
  - docker build --pull -t iloveflamingo/buildenv:1.10 .
  - docker push iloveflamingo/buildenv:1.10
  only:
  - master

.dep: &dep
  stage: test
  image: iloveflamingo/buildenv:1.10
  before_script:
  - mkdir -p "${GOPATH}/src/flamingo.me/"
  - export GODIR="${GOPATH}/src/flamingo.me/flamingo"
  - ln -sfv "$(pwd -P)" "${GODIR}"
  - /pact/pact-go_linux_amd64 daemon &
  - cd "${GODIR}"
  - dep ensure

cover flamingo:
  <<: *dep
  script:
  - go test -coverprofile cover.out ./...
  - go tool cover -func cover.out

test flamingo:
  <<: *dep
  script:
  - go test -race ./...

#vet flamingo:
#  <<: *dep
#  script:
#  - go test -vet 'all' -race ./...
#  allow_failure: true
