stages:
- prepare
- test

build docker env:
  stage: prepare
  image: docker:latest
  script:
  - cd build/docker
  - docker login -uiloveflamingobot -p${DOCKERPASSWORD}
  - docker build --pull --squash -t iloveflamingo/buildenv:1.10 .
  - docker push iloveflamingo/buildenv:1.10
  only:
  - master

test flamingo:
  stage: test
  image: iloveflamingo/buildenv:1.10
  script:
  - mkdir -p "${GOPATH}/src/flamingo.me/"
  - export GODIR="${GOPATH}/src/flamingo.me/flamingo"
  - ln -sfv "$(pwd -P)" "${GODIR}"
  - /pact/pact-go_linux_amd64 daemon &
  - cd "${GODIR}"
  - dep ensure
  - go test ./...
