stages:
- prepare
- test

docker 1.11:
  stage: prepare
  image: docker:latest
  script:
  - cd build/docker
  - docker login -uiloveflamingobot -p${DOCKERPASSWORD}
  - docker build --pull -t iloveflamingo/buildenv:1.11 -f Dockerfile-1.11 .
  - docker push iloveflamingo/buildenv:1.11
  only:
  - master

.init:
  stage: test
  image: iloveflamingo/buildenv:1.11
  cache:
    paths:
    - __gopath/pkg/mod
  before_script:
  - export GOPATH="$(pwd -P)/__gopath"
  - /pact/pact-go_linux_amd64 daemon &

cover flamingo:
  extends: .init
  script:
  - go test -coverprofile cover.out ./...
  - go tool cover -func cover.out

test flamingo:
  extends: .init
  script:
  - go test -race ./...

static-check flamingo:
  extends: .init
  script:
  - golint -set_exit_status ./...
  - go vet ./...
    #  - gocritic check-project .

vet flamingo:
  extends: .init
  script:
  - go test -vet 'all' -race ./...
