stages:
- test
- test-frontend
#- build

flamingo test:
  stage: test
  image: golang:1.9
  script:
  - export GODIR="${GOPATH}/src/flamingo"
  - go get -u github.com/golang/dep/cmd/dep
  - ln -sfv "$(pwd -P)" "${GODIR}"
  - cd "${GODIR}"
  - dep ensure -vendor-only
  - go test ./...
  cache:
    paths:
    - vendor/

frontend akl:
  stage: test-frontend
  image: aoepeople/fe-build-env:1.3.0
  script:
  - cd akl/frontend
  - yarn install
  - npm rebuild node-sass
  - yarn test
  cache:
    paths:
    - akl/frontend/node_modules/

frontend lhr:
  image: aoepeople/fe-build-env:1.3.0
  stage: test-frontend
  script:
  - cd akl/frontend
  - yarn install
  - npm rebuild node-sass
  - yarn test
  cache:
    paths:
    - akl/frontend/node_modules/

#flamingo akl:
#  stage: build
#
#flamingo lhr:
#  stage: build
