stages:
- test
- build
- build frontend
- publish

cache:
  paths:
  - akl/frontend/node_modules/
  - lhr/frontend/node_modules/
  - vendor/

test flamingo:
  stage: test
  image: thebod/goenv:0.0.1
  script:
  - export GODIR="${GOPATH}/src/flamingo"
  - ln -sfv "$(pwd -P)" "${GODIR}"
  - /pact/pact-go_linux_amd64 daemon &
  - cd "${GODIR}"
  - dep ensure -vendor-only
  - go test ./...

test frontend akl:
  stage: test
  image: aoepeople/fe-build-env:1.3.0
  script:
  - cd akl/frontend
  - yarn install
  - npm rebuild node-sass
  - yarn test

test frontend lhr:
  image: aoepeople/fe-build-env:1.3.0
  stage: test
  script:
  - cd lhr/frontend
  - yarn install
  - npm rebuild node-sass
  - yarn test

build akl:
  stage: build
  image: thebod/goenv:0.0.1
  script:
  - export GODIR="${GOPATH}/src/flamingo"
  - ln -sfv "$(pwd -P)" "${GODIR}"
  - cd "${GODIR}/akl"
  - go build .
  artifacts:
    expire_in: 2 days
    paths:
    - akl/akl
  dependencies:
  - test flamingo
  - test frontend akl

build lhr:
  stage: build
  image: thebod/goenv:0.0.1
  script:
  - export GODIR="${GOPATH}/src/flamingo"
  - ln -sfv "$(pwd -P)" "${GODIR}"
  - cd "${GODIR}/lhr"
  - go build .
  artifacts:
    expire_in: 2 days
    paths:
    - lhr/lhr
  dependencies:
  - test flamingo
  - test frontend akl

build frontend akl:
  stage: build frontend
  image: aoepeople/fe-build-env:1.3.0
  script:
  - cd akl/frontend
  - yarn run build
  artifacts:
    expire_in: 2 days
    paths:
    - akl/frontend/dist

build frontend lhr:
  image: aoepeople/fe-build-env:1.3.0
  stage: build frontend
  script:
  - cd lhr/frontend
  - yarn run build
  artifacts:
    expire_in: 2 days
    paths:
    - lhr/frontend/dist

publish akl:
  stage: publish
  image: docker
  dependencies:
  - build akl
  - build frontend akl
  script:
  - cd akl
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} docker-om3-akl.aoe.com
  - docker build -t docker-om3-akl.aoe.com/flamingo:latest .
  - docker push docker-om3-akl.aoe.com/flamingo:latest
#  only:
#  - master

publish lhr:
  stage: publish
  image: docker
  dependencies:
  - build lhr
  - build frontend lhr
  script:
  - cd lhr
  #- docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} docker-om3-lhr.aoe.com
  - docker login -u ${DOCKER_LHR_USER} -p ${DOCKER_LHR_PASSWORD} docker-om3-lhr.aoe.com
  - docker build -t docker-om3-lhr.aoe.com/flamingo:latest .
  - docker push docker-om3-lhr.aoe.com/flamingo:latest
#  only:
#  - master
