stages:
- prepare
- test

docker 1.12:
  stage: prepare
  image: docker:latest
  script:
  - cd build/docker
  - docker login -uiloveflamingobot -p${DOCKERPASSWORD}
  - docker build --pull -t iloveflamingo/buildenv:1.12 -f Dockerfile-1.12 .
  - docker push iloveflamingo/buildenv:1.12
  only:
  - master

.init:
  stage: test
  image: iloveflamingo/buildenv:1.12
  cache:
    paths:
    - __gopath/pkg/mod
  before_script:
  - export GOPATH="$(pwd -P)/__gopath"

cover flamingo:
  extends: .init
  script:
  - /pact/pact-go_linux_amd64 daemon &
  - go test -coverprofile cover.out ./...
  - go tool cover -func cover.out

test flamingo:
  extends: .init
  script:
  - /pact/pact-go_linux_amd64 daemon &
  - go test -race -vet 'all' ./...

static-check flamingo:
  extends: .init
  script:
  - golint -set_exit_status ./...
  - go vet ./...

