ignored = ["flamingo.me/flamingo"]

[[constraint]]
  name = "github.com/boj/redistore"
  version = "1.2.0"

[[constraint]]
  name = "github.com/coreos/go-oidc"
  version = "2"

[[constraint]]
  name = "github.com/ghodss/yaml"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/sessions"
  version = "1.1.0"

[[constraint]]
  name = "github.com/labstack/gommon"
  version = "0.2.1"

[[constraint]]
  name = "github.com/pact-foundation/pact-go"
  version = "0.0.8"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/robertkrimen/otto"
  source = "https://github.com/thebod/otto.git"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "github.com/zemirco/memorystore"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.7.0"

[[constraint]]
  name = "github.com/nicksnyder/go-i18n"
  branch = "master"

[[override]]
  name = "go.opencensus.io"
  source = "github.com/thebod/opencensus-go"
  branch = "jaeger_process_tags"
